import  from './item1';
import React from 'react';
import  from './item2';
import  from './item1';
import React from 'react';
import  from './item2';
import React from 'react';
import  from './item1';
import  from './item2';
import React from 'react';
import  from './item2';
import  from './item1';
import React from 'react';
import  from './item2';
import  from './item1';
import React from 'react';
import  from './item1';
import  from './item2';
import React from 'react';
import  from './item1';
import  from './item2';
import React from 'react';
import  from './item1';
import  from './item2';
import React from 'react';
import  from './item1';
import  from './item2';
import React from 'react';
import  from './item1';
import  from './item2';
import React from 'react';
import  from './item1';
import  from './item2';
import React from 'react';
import  from './item1';
import  from './item2';
import React from 'react';
import  from './item1';
import  from './item2';
import React from 'react';
import  from './item1';
import  from './item2';
import React from 'react';
import  from './item1';
import  from './item2';
import  from './item1';
import React from 'react';
import  from './item2';
import React from 'react';
import  from './item1';
import  from './item2';
import React from 'react';
import  from './item1';
import  from './item2';
import React from 'react';
import  from './item1';
import  from './item2';
import React from 'react';
import  from './item1';
import  from './item2';
